print('Hello')
print('Enter the price of first sweet: ')
sw1 = input((str()))
print('Enter the price of second sweet: ')
sw2 = input((str()))
print('Enter the price of third sweet: ')
sw3 = input((str()))
print('Enter the price of fourth sweet: ')
sw4 = input((str()))
print('Enter the price of fifth sweet: ')
sw5 = input((str()))
sw_1 = int(sw1[:-1])  # remove the p from the end only
sw_2 = int(sw2[:-1])
sw_3 = int(sw3[:-1])
sw_4 = int(sw4[:-1])
sw_5 = int(sw5[:-1])
sw_list = [sw_1, sw_2, sw_3, sw_4, sw_5]
total = sum(sw_list)
avg = float(sum(sw_list) / len(sw_list))
print('total price is:')
print(total, 'p')
print('Average price is:')
print(avg, 'p')
print('the highest price is:', max(sw_list), 'p')
print('the lowest price is:', min(sw_list), 'p')

